### ISSUE TITLE
smllib on Raspberry Pi? 

### ISSUE THREAD

**Issue by EckhardM** [spacemanspiff2007/SmlLib#5]
After testing on Ubuntu I am tried to use SmlLib on a Raspberry Pi. But the import already failed:
~~~
i@raspi:~ $ sudo python3 ./ehz2.py 
Traceback (most recent call last):
  File "./ehz2.py", line 6, in <module>
    from smllib import SmlStreamReader
  File "/usr/local/lib/python3.7/dist-packages/smllib/__init__.py", line 3, in <module>
    from smllib.sml_frame import SmlFrame                # noqa: F401
  File "/usr/local/lib/python3.7/dist-packages/smllib/sml_frame.py", line 107
    while (start := self.bytes.find(b'\x77\x07\x01', start + 1)) != -1:
                 ^
SyntaxError: invalid syntax
pi@raspi:~ $ 
~~~
Does SmlLib require Python 3.8?

**Comment by spacemanspiff2007** [comment]
Yes - as specified in the project page and on pypi.
You can/have to install at least 3.8 yourself.
